WIP ci/buildplan: Add steps for "multiple-nodes"

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -320,6 +320,185 @@ stages:
           \ IP=$( ip -f inet addr show eth0 | sed -En 's/^.*inet ([0-9.]+).*$/\\1/p'\
           \ ); echo \"Connect to this worker using:\n    ssh eve@$IP\""
     - ShellCommand:
+        name: Check if unzip and curl are installed
+        command: if ! unzip -h 2&> /dev/null; then echo "Aborting - unzip not installed
+          and required" >&2; exit 1; done; if ! curl -h 2&> /dev/null; then echo "Aborting
+          - curl not installed and required" >&2; exit 1; done
+        haltOnFailure: true
+    - ShellCommand:
+        name: Download and install Terraform
+        command: curl --retry 5 -O "https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip"
+          && sudo unzip "terraform_0.12.3_linux_amd64.zip" -d /usr/local/sbin/ &&
+          rm -f "terraform_0.12.3_linux_amd64.zip"
+        haltOnFailure: true
+    - ShellCommand:
+        name: Check that Terraform was installed
+        command: if terraform --version 2&> /dev/null; then echo "Aborting - Terraform
+          not installed and required" >&2; exit 1; done
+        haltOnFailure: true
+    - ShellCommand:
+        name: Initialize Terraform
+        command: for _ in $(seq 1 12); do terraform init && exit; rm -rf .terraform/;
+          sleep 5; done
+        haltOnFailure: true
+    - ShellCommand:
+        name: Validate Terraform deployment description
+        command: terraform validate
+        haltOnFailure: true
+    - ShellCommand:
+        name: Spawn OpenStack virtual infrastructure with Terraform
+        command: terraform apply -auto-approve
+        haltOnFailure: true
+        env:
+          OS_AUTH_URL: '%(secret:scality_cloud_auth_url)s'
+          OS_PASSWORD: '%(secret:scality_cloud_password)s'
+          OS_REGION_NAME: '%(secret:scality_cloud_region)s'
+          OS_TENANT_NAME: '%(secret:scality_cloud_tenant_name)s'
+          OS_USERNAME: '%(secret:scality_cloud_username)s'
+          TF_VAR_nodes_count: '2'
+    - ShellCommand:
+        name: Send bastion public key to nodes
+        command: for target_host in bootstrap node1; do scp -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          -3 bastion:.ssh/bastion.pub $target_host:.ssh/ && ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          $target_host cat .ssh/bastion.pub >> .ssh/authorized_keys; done
+    - ShellCommand:
+        name: Send bastion private key to bootstrap
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo mkdir -p /etc/metalk8s/pki && scp -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          -3 bastion:.ssh/bastion bootstrap:./ && ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo mv bastion /etc/metalk8s/pki/
+    - ShellCommand:
+        name: Retrieve ISO image checksum
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap curl -s -XGET -o "SHA256SUM" "%(prop:artifacts_private_url)s/SHA256SUM"
+    - ShellCommand:
+        name: Retrieve ISO image
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap bash -c 'for i in {1..20}; do echo "Attempt $i out of 20"; curl
+          -s -XGET -o "metalk8s.iso" "%(prop:artifacts_private_url)s/metalk8s.iso"
+          && exit; sleep 2; done; echo "Could not retrieve ISO after 20 attempts"
+          >&2; exit 1'
+        haltOnFailure: true
+    - ShellCommand:
+        name: Check ISO image with checksum
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sha256sum -c SHA256SUM
+        workdir: .
+    - ShellCommand:
+        name: Create ISO mountpoint
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo mkdir -p "/srv/scality/metalk8s-%(prop:metalk8s_version)s"
+        haltOnFailure: true
+    - ShellCommand:
+        name: Mount ISO image
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo mount -o loop "metalk8s.iso" "/srv/scality/metalk8s-%(prop:metalk8s_version)s"
+        haltOnFailure: true
+    - ShellCommand:
+        name: Create bootstrap configuration file
+        command: "ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config\
+          \ bootstrap sudo bash -c 'mkdir -p /etc/metalk8s; cat > /etc/metalk8s/bootstrap.yaml\
+          \ << END\napiVersion: metalk8s.scality.com/v1alpha2\nkind: BootstrapConfiguration\n\
+          networks:\n  controlPlane: 10.100.0.0/16\n  workloadPlane: 10.100.0.0/16\n\
+          ca:\n  minion: $(hostname)\napiServer:\nhost: $(ip route get 10.100.0.0\
+          \ | awk '/10.100.0.0/{ print $6 }')\narchives:\n- \"$(relpath 'metalk8s.iso')\"\
+          \nEND'"
+        haltOnFailure: true
+    - ShellCommand:
+        name: Start the bootstrap process
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap [[ -f "{{script}}" ]] || scp -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          {{script}} {host}:{{script}} && ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo bash /srv/scality/metalk8s-%(prop:metalk8s_version)s/bootstrap.sh
+          --verbose
+        haltOnFailure: true
+    - ShellCommand:
+        name: Provision Prometheus and AlertManager storage
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap [[ -f "{{script}}" ]] || scp -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          {{script}} {host}:{{script}} && ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo bash env PRODUCT_TXT=/srv/scality/metalk8s-%(prop:metalk8s_version)s/product.txt
+          PRODUCT_MOUNT=/srv/scality/metalk8s-%(prop:metalk8s_version)s eve/create-volumes.sh
+        haltOnFailure: true
+    - ShellCommand:
+        name: Enable IP-in-IP encapsulation for Calico
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap [[ -f "{{script}}" ]] || scp -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          {{script}} {host}:{{script}} && ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap bash /home/centos/scripts/enable_ipip.sh
+    - ShellCommand:
+        name: Run installation scenarii
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bastion git checkout "$BRANCH" --quiet && tox -e tests -- -m "install and
+          ci and multinodes"
+        haltOnFailure: true
+        env:
+          BRANCH: '%(prop:branch)s'
+          ISO_MOUNTPOINT: *id003
+          SSH_CONFIG: eve/workers/openstack-multiple-nodes/terraform/ssh_config
+    - ShellCommand:
+        name: Run fast tests
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bastion git checkout "$BRANCH" --quiet && tox -e tests -- -m "post and ci
+          and multinodes and not slow"
+        haltOnFailure: true
+        env:
+          BRANCH: '%(prop:branch)s'
+          ISO_MOUNTPOINT: *id003
+          SSH_CONFIG: eve/workers/openstack-multiple-nodes/terraform/ssh_config
+    - ShellCommand:
+        name: Run slow tests
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bastion git checkout "$BRANCH" --quiet && tox -e tests -- -m "post and ci
+          and multinodes and slow"
+        haltOnFailure: true
+        env:
+          BRANCH: '%(prop:branch)s'
+          ISO_MOUNTPOINT: *id003
+          SSH_CONFIG: eve/workers/openstack-multiple-nodes/terraform/ssh_config
+    - ShellCommand:
+        name: Collect logs using sosreport
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap sudo sosreport --all-logs -o metalk8s -kmetalk8s.podlogs=True
+          -o containerd -kcontainerd.all=True -kcontainerd.logs=True --batch --tmp-dir
+          /var/tmp && sudo chown eve:eve /var/tmp/sosreport*
+    - ShellCommand:
+        name: Copy artifacts for 'sosreport/single-multiple-nodes/bootstrap'
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          bootstrap mkdir -p artifacts/sosreport/single-multiple-nodes/bootstrap;
+          for artifact in /var/tmp/sosreport*; do cp -r "$artifact" artifacts/sosreport/single-multiple-nodes/bootstrap;
+          done
+    - ShellCommand:
+        name: Collect logs using sosreport
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          node1 sudo sosreport --all-logs -o metalk8s -kmetalk8s.podlogs=True -o containerd
+          -kcontainerd.all=True -kcontainerd.logs=True --batch --tmp-dir /var/tmp
+          && sudo chown eve:eve /var/tmp/sosreport*
+    - ShellCommand:
+        name: Copy artifacts for 'sosreport/single-multiple-nodes/node1'
+        command: ssh -F eve/workers/openstack-multiple-nodes/terraform/ssh_config
+          node1 mkdir -p artifacts/sosreport/single-multiple-nodes/node1; for artifact
+          in /var/tmp/sosreport*; do cp -r "$artifact" artifacts/sosreport/single-multiple-nodes/node1;
+          done
+    - ShellCommand:
+        name: Destroy Terraform-deployed infrastructure
+        command: for _ in $(seq 1 3); do terraform destroy -auto-approve && break;
+          done
+        alwaysRun: true
+        env:
+          OS_AUTH_URL: '%(secret:scality_cloud_auth_url)s'
+          OS_PASSWORD: '%(secret:scality_cloud_password)s'
+          OS_REGION_NAME: '%(secret:scality_cloud_region)s'
+          OS_TENANT_NAME: '%(secret:scality_cloud_tenant_name)s'
+          OS_USERNAME: '%(secret:scality_cloud_username)s'
+        workdir: eve/workers/openstack-multiple-nodes/terraform
+        sigtermTime: 600
+    - Upload:
+        name: Upload artifacts
+        source: *id002
+        urls:
+        - sosreport/multiple-nodes
+    - ShellCommand:
         name: Set build status to 'SUCCESSFUL' for multiple-nodes
         command: mkdir -p build_status/build_status/multiple-nodes && echo 'SUCCESSFUL'
           > build_status/build_status/multiple-nodes/final_status
